### ISSUE TITLE
Landing page has link for Plone 6 in More demo sites for you section

### ISSUE THREAD

**Issue by PriyanshuRj** [plone/plone.volto#114]
**Describe the bug**
The landing page (demo page) has a section for more demo sites which contains a self redirecting link to Plone 6 itself. Which can be removed as this is the landing page for Plone 6 demo itself.

**To Reproduce**

1. Go to https://demo.plone.org/
3. Scroll down to More demo sites for you Section
3. 2. Click on Plone 6 
4. It won't redirect anywhere because this is the demo page for Plone 6 itself

**Expected behavior**
The Plone 6 redirecting link should be removed from that section as its not a different demo page

**Comment by stevepiercy** [comment]
I think the file to edit is here: https://github.com/plone/plone.volto/blob/636b459d74487a2567f37d11616b120610c7439b/src/plone/volto/default_homepage/demo.py#L399-L400

**Comment by PriyanshuRj** [comment]
@stevepiercy  should i remove this ?

**Comment by stevepiercy** [comment]
I don't know if they should be removed. Perhaps it should be "Plone 6 (this site)" or "Plone 6 (Volto as frontend)". I'll leave that decision to the maintainers.

The link for Plone 6 Classic UI should be updated to https://classic.demo.plone.org/.

I don't know whether we should include a link to the Plone 5.2 demo site (https://52.demo.plone.org/).

Also take a good careful look at the structure of this file. What do you think would happen if you simply deleted those two lines? That's an "extra credit" question. Bonus points if you run it locally to find out. :wink:

When I edited this file, I went to the demo site, opened up my browser's web developer tools, and grabbed the JSON in the HTTP response. If the demo is "fresh" (it clears out all edits on a regular schedule), then you can use that to compare against the file in the repo. Alternatively, you can run the demo site locally. Finally you can edit the demo site through the UI, wherever it is hosted, and run a diff of the latest JSON in the HTTP response to find what needs to be changed.

**Comment by PriyanshuRj** [comment]
Hey, @stevepiercy can you please review the PR

**Comment by PriyanshuRj** [comment]
Hey, @stevepiercy  did the required changes can you review again please.

**Comment by stevepiercy** [comment]
@PriyanshuRj sorry, no. You can ask a maintainer to review and approve. You can find them in the [list of contributors for a project](https://github.com/plone/plone.volto/graphs/contributors), usually the top 5 is more than enough. Also follow the instructions from the bot in your PR. Thank you.
