### ISSUE TITLE
`volto.preview_image_link` does not work OOTB

### ISSUE THREAD

**Issue by sneridagh** [plone/plone.volto#141]
I'm trying to get the `preview_image_link` workable, but it seems that it is not working.

The scales never get into the serialization, I can't pinpoint why.

Steps to reproduce:

1.- Add the behavior `volto.preview_image_link` to the `Document` content type, remove the normal `preview_image` field to avoid confusions
2.- Add an image
3.- Select the image in the Preview Image field 
4.- Save

The serialization:

```json
{
  "@id": "http://localhost:3000/de/page/halfdome2022.jpg",
  "@type": "Image",
  "Subject": [],
  "UID": "e20b8a24ffcd49eeb2b90c47df347686",
  "description": "",
  "effective": "1969-12-30T22:00:00+00:00",
  "image_field": null,
  "image_scales": null,
  "review_state": null,
  "title": "halfdome2022.jpg",
  "type_title": "Bild"
}
```

The serializer seems to be passing the PersistentDict of the scales to the index and the metadata fields are present in the catalog for that object.
However, when the summary serializer kicks in, the value somehow is null for both. This is correct and being called:

https://github.com/plone/plone.volto/blob/main/src/plone/volto/summary.py#L9-L10

/cc @davisagli @ericof

**Comment by sneridagh** [comment]
We have custom serializers for this in every single project, even in `collective.blog`. Let's settle on one way of doing it. This has to be in line of what `Image` component expects. I'm starting to put order in there, see: https://github.com/plone/volto/pull/5939

TBH, I implemented that under the assumption that the serialization that `collective.blog` was doing was the `plone.volto`'s default... This is to return the whole image object... could be that's overkill, we have to discuss it, but at least is consistent and something that would be "expectable". Something like the summary for me is not.

Let's model also all possible responses in TS, this way we will have a better understanding of what's going on, also start unifying things.

**Comment by davisagli** [comment]
@sneridagh There are a few different cases and I'm a bit confused about which serialization you're talking about here. (Serialization of the image_preview_link field when you get the page from the content service? Serialization of the preview_image_link in the image_scales field when the page's summary serialization appears in a listing? Something else?) Please specify the URL where you got the serialization that you showed in this issue's description.

**Comment by sneridagh** [comment]
The snippet above is from the page object content serialization, what's inside of preview_image_link field in the main content endpoint.

**Comment by sneridagh** [comment]
Which seems to me like a summary of the item?

**Comment by sneridagh** [comment]
@davisagli Btw, it can be easy reproduced in demo.plone.org

**Comment by davisagli** [comment]
@sneridagh There it comes from the relation field serializer, which uses the summary serializer: https://github.com/plone/plone.restapi/blob/main/src/plone/restapi/serializer/relationfield.py#L23

The summary serializer adapts its context to IContentListingObject. Normally its context is a catalog brain, and image_scales is available from the catalog metadata.

But when it's used by the relation field serializer, the context is a full object, so the IContentListingObject adapter is [RealContentListingObject](https://github.com/plone/plone.app.contentlisting/blob/master/plone/app/contentlisting/realobject.py#L16) which does not have access to the image scales from the catalog.

For our client project we implemented an override of RealContentListingObject which adds support for getting the image_scales:
```
@adapter(IImage)
class RealContentListingObjectWithImageScales(RealContentListingObject):
    def image_scales(self):
        # This should be moved into plone.app.contentlisting at some point.
        obj = self.getObject()
        return getMultiAdapter((obj, getRequest()), IImageScalesAdapter)()
```

Like the comment says, we should backport that to the base class in plone.app.contentlisting.
