### ISSUE TITLE
Type Links does not appear in the Volto menu

### ISSUE THREAD

**Issue by wesleybl** [plone/plone.volto#145]
This is because the `nonfolderish_tabs` setting is set to False:

https://github.com/plone/plone.volto/blob/b997f4b2e8abf03a8e9ac31e8342ddc3e612a123/src/plone/volto/profiles/default/registry.xml#L3-L7

And the navigation service checks this configuration:

https://github.com/plone/plone.restapi/blob/3ad0f0534b49c9cb7ccde4d568a627d2f8e420ec/src/plone/restapi/services/navigation/get.py#L116-L117

As the Link is not folderish, it does not appear in the menu when this setting is False.

This configuration was made in this commit by @sneridagh: https://github.com/plone/plone.volto/commit/6b9426dbbe91962ca372d2b6de020bd5e87bbdc7

Why was this configuration made? How does it influence Volto? Can we leave the default value True, so that the Link type appears in the menu?

**Comment by davisagli** [comment]
@wesleybl By menu, you mean the main navigation, right?

**Comment by davisagli** [comment]
In my opinion it would make sense to change this to True, and manage specific types to include with the displayed_types setting (and/or the excludefromnav behavior for specific items)
