### ISSUE TITLE
plone.volto.multilingual must not install langauge settings

### ISSUE THREAD

**Issue by jensens** [plone/plone.volto#151]
We install English and Italian and German here:
https://github.com/plone/plone.volto/blob/main/src/plone/volto/profiles/multilingual/registry.xml

I do think we should make such a choice here. Otherwise one with other choices need to remove the language after using the profile.

Otherwise, if it is a test-profile only, not intended to be used outside of testing, it should be named explicit as such.

**Comment by davisagli** [comment]
When plone.volto becomes a distribution, it should ask as part of the site creation form what languages to enable (or at least the primary language), and update the registry setting based on that parameter.

**Comment by stevepiercy** [comment]
Apologies if this is off-topic. @davisagli's comment brought to my mind to set a default timezone (or enabling multiple timezones) for a site. Should I create a ticket to set the site's default timezone, similar to setting a default language or enabling multiple languages?

**Comment by jensens** [comment]
> When plone.volto becomes a distribution, it should ask as part of the site creation form what languages to enable (or at least the primary language), and update the registry setting based on that parameter.
> 
> So if you are creating a site with "only" the plone.volto distribution, you can specify the language there, but if you are using plone.volto as a dependency of some other policy package, you can configure the languages in the policy package.

If the profile here installs already the LRFs for the languages it is a nasty work to remove unneeded. This happened to me, and the reason I wrote this issue.
If it it does not install them, then the distribution install is not complete.

**Comment by jensens** [comment]
> Should I create a ticket to set the site's default timezone, similar to setting a default language or enabling multiple languages?

I would add such a ticket to Products.CMFPlone, because it is not volto-related.

**Comment by sneridagh** [comment]
@jensens this profile is used as a backend fixture by Volto Cypress acceptance tests. It is not intended for anything else.

**Comment by davisagli** [comment]
It is already pretty clear that it is for test purposes where it is registered: https://github.com/plone/plone.volto/blob/main/src/plone/volto/profiles.zcml#L41

Including `test` in the name would make it a bit clearer, but it's simplest to just leave it as is. I'll close this.
