### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.volto#152]
When I install just `plone.volto`, I get an error on startup:

```
Traceback (most recent call last):
...
  File "/Users/maurits/community/plone-coredev/6.1/
src/plone.volto/src/plone/volto/browser/migrate_richtext.py", line 10, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

The dependency was declared in 2.1.3, but removed in 3.1.0a3.  This is in code that is loaded conditionally only on Plone 6, so Plone 5 is save.

This would have been caught sooner if we had applied the `plone/meta` sauce on this package.  I am doing so now, but that brings in a lot of changes.  It may be better to handle that separately.  And it would be easier if it is okay to drop support for Plone 5.2.

I will have a look how we can fix the requests problem cleanly.  Current idea:

* Do not put it in `setup.py`, as it is not a hard dependency.
* Conditionally load the zcml that uses it.

Alternatively, it should also be fine to add the dependency: lots of projects want to use the requests library.

**Comment by davisagli** [comment]
@mauritsvanrees I just discussed version support for this package with @ericof and @tisto. We want to make a branch for Plone 5.2 and 6.0, and continue development for Plone 6.1 on main.

I like not making requests a hard dependency. I would list it in an extra named `migrate` or `upgrade`.

> Alternatively, it should also be fine to add the dependency: lots of projects want to use the requests library.

requests receives minimal maintenance these days. I would check if we can use its dependency urllib3 directly.

**Comment by mauritsvanrees** [comment]
For now I created this PR: https://github.com/plone/plone.volto/pull/154

We could add `requests` in an extra, but since the extra would only contain `requests` we can just tell people to add that library.
