### ISSUE TITLE
Provide an easy way to get content of child/Sibilings 

### ISSUE THREAD

**Issue by arky** [plone/plone.volto#27]
When creating a view, you often have to traverse the child elements content. You will have to create a new action to do similar to what's implemented here https://github.com/eea/eea.restapi/blob/master/src/eea/restapi/api/siblings.py

Given it is such a common task, it would be worth implementing the plone.volto

Full background discussion in the Discord thread 
https://discord.com/channels/786421998426521600/787308038050545666/910758994358972476

/cc @tiberiuichim

**Comment by djay** [comment]
@arky doesn't this belong in https://github.com/plone/volto/issues? or is it you are looking for a new restapi endpoint?

**Comment by arky** [comment]
@djay This is really an old bug back from 2021. Closing this as the issues has been resolved with restapi.
