### ISSUE TITLE
typo in /accesibility-info ID, and missing page in default site content

### ISSUE THREAD

**Issue by tkimnguyen** [plone/plone.volto#31]
In our test site for the plone.org sprint, we noticed that http://45.56.116.49/accesibility-info does not have a matching page in the default site that was created.

That is linked from the default footer

**Comment by davisagli** [comment]
This will be fixed by the combination of https://github.com/plone/volto/pull/3248 and https://github.com/plone/plone.volto/pull/93

(by removing the accessibility link; we can re-add it if someone wants to do the work to add a page to the initial content)
