### ISSUE TITLE
News Items and Events should have blocks behaviour by default

### ISSUE THREAD

**Issue by tkimnguyen** [plone/plone.volto#32]
Currently blocks behaviour is not enabled for News Items and Events. 

If we go to the Dexterity Content Types panel and enable it, we can edit a news item and see the blocks editor, but the view does not show the blocks.

**Comment by tisto** [comment]
I agree. @tiberiuichim you have an "event-details" block available somewhere, right? I guess we should create a PR that enables the blocks behavior on News and Events and a second one that adds this new event-details block.

**Comment by nileshgulia1** [comment]
+1 on having "event-details" block on core.
@tisto why we can't have `renderBlocks()` by default in `event_view`?

**Comment by nileshgulia1** [comment]
https://github.com/plone/volto/blob/1e48bbe435580f0aca0b1e09d48f6f9d7408528a/src/components/theme/View/RenderBlocks.jsx

**Comment by tiberiuichim** [comment]
One thing I think it's also important is to have the eventDetails block added to the default blocks. I think the [initialBlocks](https://github.com/plone/volto/blob/643407b4701ce9c75060ff13965d3442f1c09426/src/config/Blocks.jsx#L456) setting is supposed to set the initial blocks per content type. I have a workaround, but I think initialBlocks is the right solution. (my workaround injects the eventDetails block if it's not found in the blocks, when displaying the event.
```
const addEventDetailsBlock = (content) => {
  const hasBlock = Object.values(content.blocks).find(
    (b) => b?.['@type'] === 'eventDetails',
  );

  if (!hasBlock) {
    const uid = uuid();
    content.blocks[uid] = { '@type': 'eventDetails' };
    content.blocks_layout.items = [
      content.blocks_layout.items[0],
      uid,
      ...content.blocks_layout.items.slice(1),
    ];
  }

  return content;
};
```

```
const EventView = (props) => {
  const { intl, content } = props;
  return (
    <Container className="view-wrapper event-view">
      {hasBlocksData(content) ? (
        <>
          <RenderBlocks
            {...props}
            content={addEventDetailsBlock(content)}
          />
        </>
      ) : (
        <>
          {content.title && (
            <h1 className="documentFirstHeading">{content.title}</h1>
          )}
          {content.description && (
            <p className="documentDescription">{content.description}</p>
          )}
```

**Comment by davisagli** [comment]
Looks like this was already done
