### ISSUE TITLE
Discussion: Ship Volto/Plone 6 with/without Folder content type?

### ISSUE THREAD

**Issue by tisto** [plone/plone.volto#53]
With the new folderish Page content type in Volto, the use case for the "Folder" content type is mostly gone. The only use case that comes to mind is if the editor wants to create a folder that is not supposed to be sorted by any criteria (Collection / listing block) and the contained items are files (or images?).

Are there any other valid use cases that are not covered by the folderish Page?

If that's not the case I would argue that we shouldn't ship with a content type that has no real value any longer and that will highly confuse editors. Our editors asked us that question some time ago and I honestly couldn't come up with a sound explanation.

My personal recommendation would be to get rid of the Folder content type altogether. We can keep it disabled for integrators in case they need it.

I'd like to have an open debate about this and make a decision before we ship Plone 6.

**Comment by pbauer** [comment]
If we do this (I'm on the fence) we should probably migrate existing Folders to Documents when installing plone.volto.

**Comment by Rudd-O** [comment]
I would prefer to have simple folders that aren't documents.  Maybe the content type should not be featured prominently / should be deemphasized, but folders are useful as containers.  E.g. I want to add some files to folder and I want the listing to show, but I don't want the file listing to show for documents that contain files, if there is a Folder type I can do this via CSS, but if there isn't a Folder type then I can't do it via CSS (or any other way, really).

**Comment by davisagli** [comment]
@Rudd-O Folders were already removed, by default. I think the decision was made during the sprints this past spring.

> I want to add some files to folder and I want the listing to show the files, but I don't want the file listing to show for documents / news items that contain files. If there is a Folder type I can do this via CSS trivially, but if there isn't a Folder type then I can't do it (via CSS or any other way, really).

You can make this distinction by choosing whether or not to add a listing block.

If you really want a Folder type, it is very easy to re-enable it for your site. Just go to the Content Settings control panel, select Folder, check the "Globally addable" checkbox, and save.

**Comment by Rudd-O** [comment]
> You can make this distinction by choosing whether or not to add a listing block.

Some of us don't use Volto, y'know.

I thought the plan was to support both plain Plone and Plone + Volto, but Volto assumptions are already seeping into the codebase.

**Comment by davisagli** [comment]
@Rudd-O It's fine if you want to use Plone classic! You made this comment in the plone.volto repository, so I assumed you were using volto.

When I create a new Plone 6 site using the "Create Classic Plone site" button, the Folder type is still available:
![Screen Shot 2022-08-31 at 7 56 20 AM](https://user-images.githubusercontent.com/49014/187710503-3e88c31a-b606-4517-92f7-a3c4d879e57d.png)

If that's not working for you, maybe there is a bug. In that case, please open a new issue in CMFPlone with steps to reproduce.

**Comment by Rudd-O** [comment]
Thank you @davisagli I don't know how I did not notice the repo is the Volto repo.

**Comment by djay** [comment]
You'd have to make it clear the way to choose what's in your top level menu is now only determined by the hide from menu setting not content type. Perhaps that should be made more visible?

Seperate issue with folderish pages is that inserting an image during on add has different behaviour to inserting an image on edit after creation. I personally think this is confusing enough it should be resolved before release. 
I  know there have been many solutions over the years. I personally think simplist is just go the castle CMS way. Add dialog sets a title and then after that you redirect to the created content. Much simpler to understand and allows for the handy feature in castle you could bulk add content before editing.
Creating it with a temp Id and deleting on cancel works but I think is more complicated.

**Comment by davisagli** [comment]
@djay I agree that is an important thing to improve. Could you please open a separate issue for it in the plone/volto repository if there isn't one yet?

**Comment by djay** [comment]
> @Rudd-O Folders were already removed, by default. I think the decision was made during the sprints this past spring.
> 
> > I want to add some files to folder and I want the listing to show the files, but I don't want the file listing to show for documents / news items that contain files. If there is a Folder type I can do this via CSS trivially, but if there isn't a Folder type then I can't do it (via CSS or any other way, really).
> 
> You can make this distinction by choosing whether or not to add a listing block.
> 
> If you really want a Folder type, it is very easy to re-enable it for your site. Just go to the Content Settings control panel, select Folder, check the "Globally addable" checkbox, and save.

I think he makes a good point that styling or selecting pages acting like folders vs pages acting like pages is a bit harder. Hide from navigation could be use as a css tag in listings. But it also might nice if there was a class for pages that contain pages or files. But a bit hard to generalise. Why are images or other embeddible types of but news items aren't?
Of course a site that cares could just reenable folders

**Comment by djay** [comment]
> @djay I agree that is an important thing to improve. Could you please open a separate issue for it if there isn't one yet?

https://github.com/plone/volto/issues/3606

**Comment by Rudd-O** [comment]
@djay thanks for these comments.  Pet peeve of mine is that I have to add the news item (in my case folderish) before I can add content to it.  AAAA.  I understand this may be nigh impossible to fix without some absurd sorcery inside Plone's guts.

**Comment by djay** [comment]
> @djay thanks for these comments.  Pet peeve of mine is that I have to add the news item (in my case folderish) before I can add content to it.  AAAA.  I understand this may be nigh impossible to fix without some absurd sorcery inside Plone's guts.

@Rudd-O no not hard to fix as long as you are ok with setting the title and creating the object before you can edit it. See https://github.com/plone/volto/issues/3606. I think the advantages outweigh what you lose by being able to edit before creation.

**Comment by Rudd-O** [comment]
> no not hard to fix as long as you are ok with setting the title and creating the object as the step before being able edit it. 

Yeah that's what I mean, if I have to save the object with the title, then I would not consider #3606 "fixed".  Although an onscreen ability to save the object with all optional fields empty, and let me proceed on the same screen — doable with Volto, impossible with Plone — is probably an okay workaround.

**Comment by djay** [comment]
@Rudd-O I don't think you looked at the ticket. It has a screenshot and video of a previous similar implementation.
