### ISSUE TITLE
Typo on Volto default homepage

### ISSUE THREAD

**Issue by mliebischer** [plone/plone.volto#65]
**Describe the bug**
Hi guys, there seems to be a typo on the default home page of a new Volto installation. 

> "Volto can be **esily** themed and is highly customizable." 

esily --> easily

**To Reproduce**

1. Go to ['Volto Demo'](https://volto.kitconcept.com/)
2. See error

**Expected behavior**
The text should be "Volto can be easily themed and is highly customizable."

**Screenshots**
![image](https://user-images.githubusercontent.com/15084997/171656140-5134553e-664c-4e67-af1f-f754ff28a0a9.png)

**Software:**
- Volto 15.5.0
- Plone 5.2.6
- plone.restapi 8.20.0
- plone.volto 4.0.0a4

**Additional context**
A quick source code search reveals:
https://github.com/plone/plone.volto/blob/802ce36ca7302a65dc5741f274417809aa5c8884/src/plone/volto/default_homepage/default.py#L61
https://github.com/plone/plone.volto/blob/802ce36ca7302a65dc5741f274417809aa5c8884/src/plone/volto/default_homepage/default.py#L348
https://github.com/plone/plone.volto/blob/802ce36ca7302a65dc5741f274417809aa5c8884/src/plone/volto/default_homepage/default.py#L369

Note: The same problem seems to occur with "[eea.volto.policy](https://github.com/eea/eea.volto.policy/blob/9d1c03506b834ee27802d3e2760b485ce549ef6b/eea/volto/policy/setuphandlers.py#L121)" as well.

**Comment by rohnsha0** [comment]
I'll fix the same!
