### ISSUE TITLE
Build uses released version of plone.volto

### ISSUE THREAD

**Issue by tisto** [plone/plone.volto#69]
The local build (and maybe even the CI build) currently use a checked-out version of plone.volto instead of the real package:

```
$ make
...
Installing collected packages: plone.volto
  Attempting uninstall: plone.volto
    Found existing installation: plone.volto 4.0.0a4
    Uninstalling plone.volto-4.0.0a4:
      Successfully uninstalled plone.volto-4.0.0a4
  Running setup.py develop for plone.volto
Successfully installed plone.volto-4.0.0a5.dev0
```

This is due to the fact that we are missing a line in our buildout file:

```
plone.volto =
```

to make sure we use the local version.

**Comment by rohnsha0** [comment]
But do I need to add this line to the codebase?

**Comment by davisagli** [comment]
From what I can see this is working correctly with both the buildout and with make. Your log shows a local package being installed, as evidenced by the .dev0 version.
