### ISSUE TITLE
Adding the image_scales metadata to the default serialization

### ISSUE THREAD

**Issue by ericof** [plone/plone.volto#74]

**Comment by davisagli** [comment]
Should this be in plone.restapi rather than plone.volto?

I think we want it added in several places:
- summary serializer
- image field serializer
- resolveuid block serialization transform when the referenced item is an image

**Comment by ericof** [comment]
In the past we decided to add it here as it was used only for Volto sites. I think we could move it back to plone.restapi before the final version of plone.volto

**Comment by davisagli** [comment]
@ericof that would make sense if it was only for the preview_image, but the `image_scales` metadata includes scales from all image fields so I think it's generically useful
